repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check accounts config common labbridge workspaces tests
        language: system
        pass_filenames: false
