"""Studio orchestration labels for the public experimental observable-field API."""

FIELD_ANALYSIS_KIND = "OBSERVABLE_SPATIAL_FIELD"
FIELD_ANALYSIS_LABEL = "Observable Spatial Agencity Field"
FIELD_SCIENTIFIC_STATUS = "EXPERIMENTAL"
FIELD_PUBLIC_FUNCTION = "agencitylab.fields.compute_agencity_field"
FIELD_MODEL = "observable_agencity_field"
FIELD_RESULT_SCHEMA_VERSION = "field-v1"

SPATIAL_AXES_SAMPLE_INDEX = "SAMPLE_INDEX"
SPATIAL_AXES_EXPLICIT = "EXPLICIT"

PARAMETER_MODE_SCALAR = "SCALAR"
PARAMETER_MODE_SPATIAL = "SPATIAL_MAP"
POWER_MODE_SPACETIME = "SPACETIME_MAP"
WINDOW_MODE_UNSPECIFIED = "UNSPECIFIED"
